# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20171010_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appuser',
            name='userId',
            field=models.CharField(max_length=32),
        ),
    ]
