# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_remove_schedule_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.Appuser'),
            preserve_default=False,
        ),
    ]
