# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_schedule_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='busyType',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
